### ISSUE TITLE
Use font-awesome stars for reviews' ratings, instead of 'ugly' gifs

### ISSUE THREAD

**Issue by lat9** [lat9/ZCA-Bootstrap-Template#11]
For the various review-related pages.

**Comment by drbyte** [comment]
Random thought; apologies if this has already been considered and decided against: Should the helper function allow for a `0` rating and just skip outputting anything? ... instead of defaulting to `1` ? 
I realize this should rarely happen since default ZC code requires a rating, and I'm probably over-thinking it without digging deeply enough.

**Comment by lat9** [comment]
Not so random; I'd considered it but was trying to keep with the ZC base model.  I'll get that updated real-soon-now.
