### ISSUE TITLE
Improvements to viewing on mobile devices

### ISSUE THREAD

**Issue by lat9** [lat9/ZCA-Bootstrap-Template#17]
This is a 'bit-bucket' issue to gather various mobile-interface improvements for the v3.0.1 release of this template.

**Comment by drbyte** [comment]
Should we do invasive changes to re-order the display of the "forgotten pwd" vs "sign in" buttons? Or leave it simple?
(And the Sign Up button's column seems to have no padding).
![forgot-vs-button](https://user-images.githubusercontent.com/404472/103153630-dff87780-475f-11eb-877a-537460a5d00a.jpg)

**Comment by drbyte** [comment]
Order History doesn't change display for mobile. Instead it's a scrollable (left-right) table.
<img width="1136" alt="Screen Shot 2020-12-26 at 9 53 00 AM" src="https://user-images.githubusercontent.com/404472/103153690-55fcde80-4760-11eb-8a5e-c21ac5f42553.png">
<img width="632" alt="Screen Shot 2020-12-26 at 9 53 17 AM" src="https://user-images.githubusercontent.com/404472/103153691-58f7cf00-4760-11eb-9287-418dccec4b04.png">

**Comment by drbyte** [comment]
Row-based product-listing is "usable" but a little tough visually. Changing this is probably quite invasive, and I think most stores are likely to opt for cells/grid instead of table.

<img width="642" alt="Screen Shot 2020-12-26 at 10 09 08 AM" src="https://user-images.githubusercontent.com/404472/103153986-ac6b1c80-4762-11eb-9b32-55b23e08332a.png">

**Comment by lat9** [comment]
> 
> 
> Row-based product-listing is "usable" but a little tough visually. Changing this is probably quite invasive, and I think most stores are likely to opt for cells/grid instead of table.
> 
> <img alt="Screen Shot 2020-12-26 at 10 09 08 AM" width="642" src="https://user-images.githubusercontent.com/404472/103153986-ac6b1c80-4762-11eb-9b32-55b23e08332a.png">
> 
> <img alt="Screen Shot 2020-12-26 at 10 15 59 AM" width="511" src="https://user-images.githubusercontent.com/404472/103154119-7da17600-4763-11eb-9496-f5aa4ade34f2.png">

Agreed; that row-based listing is pretty lame.

**Comment by lat9** [comment]
> 
> 
> Order History doesn't change display for mobile. Instead it's a scrollable (left-right) table.
> <img alt="Screen Shot 2020-12-26 at 9 53 00 AM" width="1136" src="https://user-images.githubusercontent.com/404472/103153690-55fcde80-4760-11eb-8a5e-c21ac5f42553.png">
> <img alt="Screen Shot 2020-12-26 at 9 53 17 AM" width="632" src="https://user-images.githubusercontent.com/404472/103153691-58f7cf00-4760-11eb-9287-418dccec4b04.png">

Hmm, that's not pretty either.

**Comment by lat9** [comment]
What tool are you using to view those pages with `iStuff` (or is that just with your `iStuff`)?

**Comment by drbyte** [comment]
I'm using the free https://responsively.app -- very helpful for specifying which devices to model, and look at them all at the same time.
I only selected mostly iOS mobiles because their screen sizes match up nicely with the more common breakpoints, not because of any affinity to one device over another.
