### ISSUE TITLE
Add 'role="button"' to AJAX search header link to improve SEO rating

### ISSUE THREAD

**Issue by OldNGreyBMR** [lat9/ZCA-Bootstrap-Template#246]
This is minor to raise my SEO rating in Lighthouse. This improved the rating from 73 to 82.

In bootstrap the AJAX version of the search header is in the file 
\includes\templates\bootstrap\sideboxes\tpl_ajax_search_header.php and is an uncrawlable link because it is <a href 
This is complained about by Lighthouse under the SEO section.

The body of the original file is:

```
$content = '<ul class="navbar-nav ml-auto">' . PHP_EOL;
$content .= '    <li class="nav-item"><a href="javascript:void(0);" id="search-icon" class="nav-link" aria-label="' . BUTTON_SEARCH_ALT . '"><i class="fas fa-2x fa-search"></i></a></li>' . PHP_EOL;
$content .= '</ul>' . PHP_EOL;
```

I changed the link to a button

```
$content = '<ul class="navbar-nav ml-auto">' . PHP_EOL;
$content .= '    <li ><button type="button" id="search-icon" class="nav-link" aria-label="' . BUTTON_SEARCH_ALT . '"><i class="fas fa-2x fa-search"></i></button></li>' . PHP_EOL;
$content .= '</ul>' . PHP_EOL;
```

and also added the following to my template css file to match my color scheme

```
button .nav-link {
  display: inline-block;
  position: relative;
  background-color: transparent;
  border: 0;
  padding: 0;
  color: #ffffff;
}
```

**Comment by lat9** [comment]
Using the built-in Chrome browser Lighthouse validation, the SEO score on a _fairly_ default bootstrap template went from 85 to 92 by simply adding that `role="button"` to the associated link ... so that's what I'm going with!

**Comment by OldNGreyBMR** [comment]
Very nice and simple.
Using Lighthouse on std bootstrap pushed the rating from 82 to 91. On my
template version (bootstrap clone) with an SEO rating of 100 changing to
your role="button"  did not affect the rating at all.
I prefer your solution.

**Comment by dbltoe** [comment]
Sorry to be late with this but part of the problem is the javascript in at least one tester.

Perhaps a simpler answer is 

`$content.='    <li class="nav-item"><button type="button" id="search-icon" class="nav-button" aria-label="' . BUTTON_SEARCH_ALT . '"><i class="fas fa-2x fa-search"></i></button></li>' . PHP_EOL;`

That validates HTML and Accessibility

When I turn off the Accessibility widget (it has a couple of errors we are working on) and test Lighthouse from an incognito browser (best test) I get 100, 98, 100,100.  With the 98 due to the EZpages header level
