### ISSUE TITLE
Checkout button colour

### ISSUE THREAD

**Issue by torvista** [lat9/ZCA-Bootstrap-Template#282]
![Screenshot 2023-08-22 173630](https://github.com/lat9/ZCA-Bootstrap-Template/assets/4391026/6cd7c87f-d5e9-4e79-b7bc-7430d49de51d)
Should not this and the other checkout steps be a green for go, instead of yellow for warning?

**Comment by dbltoe** [comment]
![image](https://github.com/lat9/ZCA-Bootstrap-Template/assets/5122886/f25f9230-503e-4b42-a54e-4f75e1a8e92a)
3.6 and a couple of versions prior to that

**Comment by dbltoe** [comment]
Here's the reasoning.  Since "checkout continue" is a separate section, the colors as shown assist the owner in finding them in the color list.
The point was for it to be accessible out of the box but easily identifiable for changes to match the desired color scheme and it sort of stands out as something they might want to change.

**Comment by torvista** [comment]
I know there is little left to chance with colours/your input, but I had to ask!

**Comment by dbltoe** [comment]
'twas a perfectly valid question.  I hope at some point to have a cheat sheet that says which items must meet what contrast.  It will include "things to change in the default" or something like that.

**Comment by lat9** [comment]
FWIW, the checkout-step buttons' coloring mimics the world's largest online store.  Hint, starts with an **A**.

**Comment by torvista** [comment]
Haha, design is not my forte!
