### ISSUE TITLE
Strip immaterial date comments from `$template_info`

### ISSUE THREAD

**Issue by proseLA** [lat9/ZCA-Bootstrap-Template#389]
if you are going to keep these stamps, can we do something to have an accurate reflection of where we are?

https://github.com/lat9/ZCA-Bootstrap-Template/blob/bc632e533527d465919a0469c2e24be27a0b5321/includes/templates/bootstrap/template_info.php#L5-L10

**Comment by lat9** [comment]
I'm not sure what you mean.  I made a change in Bootstrap 3.6.4 so that I didn't need to change this file too on every release (using the release's configuration setting).
https://github.com/lat9/ZCA-Bootstrap-Template/blob/bc632e533527d465919a0469c2e24be27a0b5321/includes/templates/bootstrap/template_info.php#L5-L14

**Comment by proseLA** [comment]
can we put a date on this file?  and get rid of the 2005-11-05?

i can not keep track of which release happened when on all of the numerous plugins of yours that i attempt to use in an effort to help with their development.

**Comment by lat9** [comment]
I can certainly remove the 2005-11-05 date, but as mentioned above the whole point of line 13 was so that this file doesn't have to be updated with each release.  The plugin's current version can be found in the admin's init_bootstrap_template_admin.php.

**Comment by proseLA** [comment]
yes.  remove all of that stuff that is completely misleading...  that would be my preference...
