### ISSUE TITLE
More information in mobile menu

### ISSUE THREAD

**Issue by ms1225** [lat9/ZCA-Bootstrap-Template#87]
More of a possible future addition/feature request than a bug, but it would be help to have the ability to easily turn on or off the more information side box in the mobile menu.

**Comment by lat9** [comment]
Having (finally!) reviewed this request, I'm finding it more of a bug than a feature, since the "More Information" side-box isn't included in the mobile-menu, even if it's enabled for the full-up desktop display.

I would have gone down a path suggesting the use of the admin's `Layout Boxes Controller` and setting the `Single Column Status` to ON ... but those "Single Column" settings were removed from zc158 via [this](https://github.com/zencart/zencart/pull/4321) base Zen Cart PR.

Given the above PR, if the "More Information" side-box is currently enabled (either left- or right-side) for the template, those links will be included in the mobile-menu after the "Information" side-box elements and prior to any EZ-Pages side-box elements.
